### ISSUE TITLE
Authentication settings were reset

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#75]
Hello, 

we changed to SAML2 authentication. Which was working quite well. Sine yesterday this settings is somehow not appyling anymore and jenkins is asking for login again. 

As we have no admin password we're not able to login.

Is their a default password or way to reset ?

**Comment by fwilhe** [comment]
Hi,

this sounds bad, I would like to understand what happened. A more detailed report of your setup and what happened yesterday would be interesting, if it contains not publishable info you can also reach out by mail at florian.wilhelm02@sap.com

We introduced a default password for admin in march as described [here](https://github.com/SAP/devops-docker-cx-server/blob/master/cx-server-companion/life-cycle-scripts/CX-SERVER-SECURITY.md). This should _only_ apply if your instance is not secured, and leave it as is otherwise. Anyway, try running `./cx-server initial-credentials`, this should give you the admin password.

For troubleshooting, the logs of cx-server at around the time of the last restart of Jenkins might be useful.

I would also be available for a remote session to look into the issue directly if that makes sense.
